from pages.base_page import BasePage
class AddAMatchForm(BasePage):
    header_xpath = "//header"
    main_page_button_xpath = "//*/ul[1]/div[1]"
    players_button_xpath = "//*/ul[1]/div[2]"
    player_button_xpath = "//*/ul[2]/div[1]"
    matches_button_xpath = "//*/ul[2]/div[2]"
    reports_button_xpath = "//*/ul[2]/div[3]"
    changing_language_button_xpath = "//*/ul[3]/div[1]"
    sign_out_button_xpath = "//*/ul[3]/div[2]"
    form_header_xpath = "//*/form/div[1]/div/span"
    my_team_label_xpath = "//label[text()='My team']"
    my_team_input_xpath = "//*/div[1]/div/div/input"
    enemy_team_label_xpath = "//label[text()='Enemy team']"
    enemy_team_input_xpath = "//*/div[2]/div/div/input"
    my_team_score_label_xpath = "//label[text()='My team score']"
    my_team_score_input_xpath = "//*/div[3]/div/div/input"
    enemy_team_score_label_xpath = "//label[text()='Enemy team score']"
    enemy_team_score_input_xpath = "//*/div[4]/div/div/input"
    date_label_xpath = "//label[text()='Date']"
    date_input_xpath = "//*/div[5]/div/div/input"
    match_at_home_label_xpath = "//*[text()='Match at home']"
    match_at_home_input_xpath = "//*/label[1]/span[1]/span[1]/input"
    match_out_home_label_xpath = "//*[text()='Match out home']"
    match_out_home_input_xpath = "//*/label[2]/span[1]/span[1]/input"
    tshirt_color_label_xpath = "//label[text()='T-shirt color']"
    tshirt_color_input_xpath = "//*/div[7]/div/div/input"
    league_label_xpath = "//label[text()='League']"
    league_input_xpath = "//*/div[8]/div/div/input"
    time_played_label_xpath = "//label[text()='Time played']"
    time_played_input_xpath = "//*/div[9]/div/div/input"
    number_label_xpath = "//label[text()='Number']"
    number_input_xpath = "//*/div[10]/div/div/input"
    web_match_label_xpath = "//label[text()='Web match']"
    web_match_input_xpath = "//*/div[11]/div/div/input"
    general_label_xpath = "//label[text()='General']"
    general_input_xpath = "//*/div[12]/div/div/input"
    rating_label_xpath = "//label[text()='Rating']"
    rating_input_xpath = "//*/div[13]/div/div/input"
    submit_button_xpath = "//*/div[3]/button[1]"
    clear_button_xpath = "//*/div[3]/button[2]"
pass
